pyms:
  requests: true
  swagger:
    path: "swagger"
    file: "swagger.yaml"
ms:
  DEBUG: false
  TESTING: false
  APP_NAME: Template
  APPLICATION_ROOT : /template
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SECRET_KEY: "gjr39dkjn344_!67#"
  DATABASE: db.sqlite3
  SQLALCHEMY_DATABASE_URI: sqlite:////tmp/db.sqlite3