# interno
kind: Service
apiVersion: v1
kind: Service
metadata:
  name: template
spec:
  selector:
    app: template
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: "Local"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: template
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: template:v1
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: template
    servicePort: 5000