# interno
kind: Service
apiVersion: v1
metadata:
  name: template
spec:
  selector:
    app: template
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
# externo
apiVersion: v1
kind: Service
metadata:
  name: template-external
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: template
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 62.82.24.134/32
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: template
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: template:latest
          ports:
            - name: http
              containerPort: 5000